steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us.gcr.io/sentryio/session-replay-analyzer:$COMMIT_SHA",
        ".",
      ]
images: ["us.gcr.io/sentryio/session-replay-analyzer:$COMMIT_SHA"]
