steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us.gcr.io/internal-sentry/session-replay-analyzer:$COMMIT_SHA",
        "session-replay-analyzer",
      ]
images: ["us.gcr.io/internal-sentry/session-replay-analyzer:$COMMIT_SHA"]
